hero_finished
dyatskovskiy/web-wizards-project pull request #4
Opened 2023-07-03 19:01 UTC by Artemskyba

2023-07-03 23:51 UTC, dyatskovskiy requested changes
Все супер :1st_place_medal: 
Есть только 2 небольшие правки на пару минут = )

2023-07-03 23:51 UTC, dyatskovskiy commented on src/css/hero.css
> +  font-family: DM Sans;
фонт фемили убрать, т.к. добавили в дефолты

2023-07-03 23:51 UTC, dyatskovskiy commented on src/css/hero.css
> +  background-color: var(--medium-white);
Не подтягивается цвет бг, некорректное название переменной
ниже так же
скопируй с дефолта

2023-07-04 09:01 UTC, Artemskyba commented on src/css/hero.css
> +  font-family: DM Sans;
done

2023-07-04 09:02 UTC, Artemskyba commented on src/css/hero.css
> +  background-color: var(--medium-white);
:root {
  --medium-white: #f9f7f4;
}

цвет добавлен у меня в цсс файле, так как этого цвета не было в дефолте

2023-07-04 16:07 UTC, dyatskovskiy approved these changes
Всё гуд

2023-07-04 16:07 UTC, dyatskovskiy commented on src/css/hero.css
> +  background-color: var(--medium-white);
Понятно, принято, готово)

2023-07-04 16:07 UTC, merged